AllCops:
  # Rubyのバージョン指定
  TargetRubyVersion: 2.6.5

# クラス名Moduleの説明をなしでもOKとする
Style/Documentation:
  Enabled: false

# 日本語でのコメントを許可
Style/AsciiComments:
  Enabled: false

# メソッドの引数の文字数を２文字以上とする
Naming/MethodParameterName:
  MinNameLength: 2

# １行の長さのMAXを150文字とする
Layout/LineLength:
  Max: 150

# メソッドの行数をコメントを除いて５０行までとする
Metrics/MethodLength:
  CountComments: true
  Max: 50

# if文の実行結果が４行以上の場合にチェックするように設定する
Style/GuardClause:
  MinBodyLength: 4

Style/IfUnlessModifier:
  Enabled: false

# メソッドの複雑度を７→１８に変更
# ※複雑度の計算方法は「https://github.com/bbatsov/rubocop/blob/master/lib/rubocop/cop/metrics/perceived_complexity.rb」
Metrics/PerceivedComplexity:
  Max: 18

# メソッドの循環的複雑度を６→１５に変更
# ※循環的複雑度の計算方法は「https://github.com/bbatsov/rubocop/blob/master/lib/rubocop/cop/metrics/cyclomatic_complexity.rb」
Metrics/CyclomaticComplexity:
  Max: 15

# メソッドのABC sizeチェックの合計ポイントを１５→４０に変更
# ABC sizeチェックの計算方法は「https://github.com/rubocop-hq/rubocop/blob/master/lib/rubocop/cop/metrics/abc_size.rb」
Metrics/AbcSize:
  Max: 40

# クラスの行数（コメントは除いて）を100→150に変更
Metrics/ClassLength:
  Max: 150

# モジュールの行数（コメントは除いて）を100→150に変更
Metrics/ModuleLength:
  Max: 150

# https://docs.rubocop.org/en/stable/cops_layout/#layoutspacearoundmethodcalloperator
Layout/SpaceAroundMethodCallOperator:
  Enabled: true

# https://docs.rubocop.org/en/latest/cops_lint/#lintraiseexception
Lint/RaiseException:
  Enabled: true

# https://docs.rubocop.org/en/latest/cops_lint/#lintstructnewoverride
Lint/StructNewOverride:
  Enabled: true

# https://docs.rubocop.org/en/latest/cops_style/#styleexponentialnotation
Style/ExponentialNotation:
  Enabled: true

# https://docs.rubocop.org/en/latest/cops_style/#stylehasheachmethods
Style/HashEachMethods:
  Enabled: true

# https://docs.rubocop.org/en/latest/cops_style/#stylehashtransformkeys
Style/HashTransformKeys:
  Enabled: true

# https://docs.rubocop.org/en/latest/cops_style/#stylehashtransformvalues
Style/HashTransformValues:
  Enabled: true

# https://docs.rubocop.org/rubocop/cops_layout.html#layoutemptylinesaroundattributeaccessor
Layout/EmptyLinesAroundAttributeAccessor:
  Enabled: true

# https://docs.rubocop.org/rubocop/0.85/cops_lint.html#lintdeprecatedopensslconstant
Lint/DeprecatedOpenSSLConstant:
  Enabled: true

# https://docs.rubocop.org/rubocop/cops_lint.html#lintduplicateelsifcondition
Lint/DuplicateElsifCondition:
  Enabled: true

# https://docs.rubocop.org/rubocop/0.85/cops_lint.html#lintmixedregexpcapturetypes
Lint/MixedRegexpCaptureTypes:
  Enabled: true

# https://docs.rubocop.org/rubocop/cops_style.html#styleaccessorgrouping
Style/AccessorGrouping:
  Enabled: true

# https://docs.rubocop.org/rubocop/0.88/cops_style.html#stylearraycoercion
Style/ArrayCoercion:
  Enabled: true

# https://docs.rubocop.org/rubocop/0.87/cops_style.html#stylebisectedattraccessor
Style/BisectedAttrAccessor:
  Enabled: true

# https://docs.rubocop.org/rubocop/0.88/cops_style.html#stylecaselikeif
Style/CaseLikeIf:
  Enabled: true

# https://docs.rubocop.org/rubocop/cops_style.html#stylehashaslastarrayitem
Style/HashAsLastArrayItem:
  Enabled: true

# https://docs.rubocop.org/rubocop/cops_style.html#stylehashlikecase
Style/HashLikeCase:
  Enabled: true

# https://docs.rubocop.org/rubocop/0.87/cops_style.html#styleredundantassignment
Style/RedundantAssignment:
  Enabled: true

# https://docs.rubocop.org/rubocop/0.86/cops_style.html#styleredundantfetchblock
Style/RedundantFetchBlock:
  Enabled: true

# https://docs.rubocop.org/rubocop/cops_style.html#styleredundantfileextensioninrequire
Style/RedundantFileExtensionInRequire:
  Enabled: true

# https://docs.rubocop.org/rubocop/0.85/cops_style.html#styleredundantregexpcharacterclass
Style/RedundantRegexpCharacterClass:
  Enabled: true

# https://docs.rubocop.org/rubocop/0.85/cops_style.html#styleredundantregexpescape
Style/RedundantRegexpEscape:
  Enabled: true

# https://docs.rubocop.org/rubocop/0.85/cops_style.html#styleslicingwithrange
Style/SlicingWithRange:
  Enabled: true
