name: CI

on:
  workflow_dispatch:
  push:
  pull_request:
    types: opened

jobs:
  ci:
    strategy:
      # いずれかのmatrixジョブが失敗した場合にGitHubは進行中のジョブをすべてキャンセルします
      fail-fast: false
      matrix:
        os: [ubuntu, macos]
        ruby: [2.6, 2.7]
    runs-on: ${{ matrix.os }}-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby
        # ref: https://github.com/ruby/setup-ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          # https://github.com/ruby/setup-ruby#caching-bundle-install-automatically
          bundler-cache: true
      - name: Install dependencies
        run: bundle install
      - name: Run Rubocop
        run:  bundle exec rubocop
      - name: Run RSpec
        run: bundle exec rspec
      - name: Upload test coverage
        id: upload-test-coverage
        uses: ./.github/actions/upload-test-coverage
      - name: Display test coverage in summary
        run: |
          coverage_value=${{ steps.upload-test-coverage.outputs.coverage-value }}
          echo "# Coverage report: $coverage_value%" >> $GITHUB_STEP_SUMMARY
      # https://github.com/marketplace/actions/action-slack
      - name: Github Actions notify to Slack
        uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          fields: repo,message,commit,author,action,eventName,ref,workflow,job,took
          mention: 'here'
          if_mention: failure
        env:
          GITHUB_TOKEN: ${{ github.token }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          MATRIX_CONTEXT: ${{ toJson(matrix) }}
        if: always()
